# Generated by Django 6.1 on 2026-08-31 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SourceDonnees', '0001_initial'),
        ('importations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('date_transaction', models.DateTimeField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('devise', models.CharField(max_length=10)),
                ('nom_emetteur', models.CharField(blank=True, max_length=150)),
                ('nom_beneficiaire', models.CharField(blank=True, max_length=150)),
                ('reference_externe', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('RAPPROCHEE', 'Rapprochée'), ('ANOMALIE', 'Anomalie'), ('NON_RAPPROCHEE', 'Non rapprochée')], default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fichier_importe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='importations.fichierimporte')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='SourceDonnees.sourcedonnees')),
            ],
        ),
    ]
