# Generated by Django 6.1 on 2026-09-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='frais_envoi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mttc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type_operation',
            field=models.CharField(blank=True, choices=[('ENVOI', 'Envoi'), ('RETRAIT', 'Retrait / Paiement'), ('REMBOURSEMENT', 'Remboursement')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='devise',
            field=models.CharField(default='XAF', max_length=10),
        ),
    ]
