# Generated by Django 6.1 on 2026-08-31 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SourceDonnees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichierImporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='imports/')),
                ('format_fichier', models.CharField(max_length=10)),
                ('date_importation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TRAITE', 'Traité'), ('ERREUR', 'Erreur')], default='EN_ATTENTE', max_length=20)),
                ('nombre_transactions', models.PositiveIntegerField(default=0)),
                ('message_erreur', models.TextField(blank=True)),
                ('importe_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichiers_importes', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichiers', to='SourceDonnees.sourcedonnees')),
            ],
        ),
    ]
