# Generated by Django 6.1 on 2026-09-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichierimporte',
            name='empreinte',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fichierimporte',
            name='type_operation',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
