# Generated by Django 6.1 on 2026-09-14 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapprochement', '0002_completer_modeles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondance',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondance',
            name='validee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='correspondance',
            name='validee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondances_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rapprochement',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapprochement',
            name='valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rapprochement',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapprochements_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='statut',
            field=models.CharField(choices=[('NON_TRAITEE', 'Non traitée'), ('EN_COURS', 'En cours'), ('RESOLUE', 'Résolue')], default='NON_TRAITEE', max_length=20),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='type_anomalie',
            field=models.CharField(choices=[('MONTANT', 'Différence de montant'), ('TVA', 'Différence de TVA'), ('TTA', 'Différence de TTA'), ('CTE', 'Différence de CTE'), ('MTTC', 'Différence de MTTC'), ('DATE', 'Différence de date'), ('REFERENCE', 'Référence différente'), ('DONNEES', 'Données différentes'), ('REGLEMENTATION', 'Non-conformité réglementaire'), ('ABSENCE', 'Transaction absente'), ('DOUBLON', 'Transaction en double'), ('AUTRE', 'Autre')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rapprochement',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('TERMINE_AVEC_ANOMALIES', 'Terminé avec anomalies')], default='EN_COURS', max_length=30),
        ),
    ]
